receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
  transform/tracestate_sampling:
    trace_statements:
      - context: span
        statements:
          - set(attributes["SampleRate"], ParseKeyValue(trace_state["hny"], ":")["sr"])

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "$HONEYCOMB_API_KEY"

service:
  pipelines:
    traces/default:
      receivers: [otlp]
      processors: [transform/tracestate_sampling]
      exporters: [oltp, debug]